version: "2"
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: poketeam
    volumes:
      - ./database:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_HOST=mysql
    restart: always
    ports:
      - 8081:80
    volumes:
      - /sessions
    links:
      - mysql